# Generated by Django 3.2.7 on 2021-09-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210925_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.manufacturer'),
            preserve_default=False,
        ),
    ]
