# Generated by Django 3.2.7 on 2021-09-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210927_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_shop', models.CharField(default='Название магазина', max_length=200, unique=True)),
                ('username', models.CharField(default='Название магазина', max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='shops',
        ),
    ]
