# Generated by Django 3.2.7 on 2021-09-27 07:05

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Category', max_length=30, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='title',
            field=models.CharField(default='Manufacturer', max_length=50, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default='description', verbose_name='Есть в наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(default='description', to='shop.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='description', verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(default='model', max_length=50, verbose_name='Модель товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='description', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='model'),
        ),
    ]
