# Generated by Django 3.2.7 on 2021-09-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210927_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
